# Manual Deployment Instructions for TuDestino
# Ejecuta estos comandos uno por uno en el servidor

echo "🚀 MANUAL DEPLOYMENT GUIDE - TuDestino"
echo "======================================"
echo ""
echo "1. Conectarse al servidor:"
echo "   ssh root@217.154.179.113"
echo "   Contraseña: xjuBTnE2"
echo ""

echo "2. Actualizar sistema:"
echo "   apt update && apt upgrade -y"
echo ""

echo "3. Instalar dependencias básicas:"
echo "   apt install -y curl wget git nginx mysql-server"
echo ""

echo "4. Instalar Node.js 20:"
echo "   curl -fsSL https://deb.nodesource.com/setup_20.x | bash -"
echo "   apt install -y nodejs"
echo "   npm install -g pm2"
echo ""

echo "5. Configurar MySQL:"
echo "   systemctl start mysql"
echo "   systemctl enable mysql"
echo "   mysql -e \"CREATE DATABASE IF NOT EXISTS tudestino;\""
echo "   mysql -e \"CREATE USER IF NOT EXISTS 'tudestino'@'localhost' IDENTIFIED BY 'tudestino123';\""
echo "   mysql -e \"GRANT ALL PRIVILEGES ON tudestino.* TO 'tudestino'@'localhost';\""
echo "   mysql -e \"FLUSH PRIVILEGES;\""
echo ""

echo "6. Clonar repositorio:"
echo "   cd /var/www"
echo "   rm -rf tudestino"
echo "   git clone https://github.com/qipuh/tudestino.git tudestino"
echo "   cd tudestino"
echo ""

echo "7. Instalar dependencias del proyecto:"
echo "   npm install"
echo "   npm run build:web"
echo ""

echo "8. Configurar variables de entorno para la API:"
echo "   cd /var/www/tudestino/apps/api"
echo "   cat > .env << 'EOF'"
echo "NODE_ENV=production"
echo "PORT=3000"
echo "DB_HOST=localhost"
echo "DB_PORT=3306"
echo "DB_NAME=tudestino"
echo "DB_USER=tudestino"
echo "DB_PASSWORD=tudestino123"
echo "JWT_SECRET=\$(openssl rand -hex 32)"
echo "FRONTEND_URL=https://tudestino.lat"
echo "BACKEND_URL=https://api.tudestino.lat"
echo "EOF"
echo ""

echo "9. Configurar ecosystem PM2:"
echo "   cd /var/www/tudestino/apps/api"
echo "   cat > ecosystem.config.cjs << 'EOF'"
echo "module.exports = {"
echo "  apps: [{"
echo "    name: 'tudestino-api',"
echo "    script: 'src/index.js',"
echo "    cwd: '/var/www/tudestino/apps/api',"
echo "    instances: 'max',"
echo "    exec_mode: 'cluster',"
echo "    env: {"
echo "      NODE_ENV: 'production',"
echo "      PORT: 3000"
echo "    },"
echo "    error_file: '/var/log/pm2/tudestino-api-error.log',"
echo "    out_file: '/var/log/pm2/tudestino-api-out.log',"
echo "    log_file: '/var/log/pm2/tudestino-api.log',"
echo "    time: true,"
echo "    autorestart: true,"
echo "    watch: false,"
echo "    max_memory_restart: '1G'"
echo "  }]"
echo "};"
echo "EOF"
echo ""

echo "10. Configurar Nginx para el dominio principal:"
echo "    cat > /etc/nginx/sites-available/tudestino.lat << 'EOF'"
echo "server {"
echo "    listen 80;"
echo "    server_name tudestino.lat www.tudestino.lat;"
echo "    return 301 https://\$server_name\$request_uri;"
echo "}"
echo ""
echo "server {"
echo "    listen 443 ssl http2;"
echo "    server_name tudestino.lat www.tudestino.lat;"
echo "    "
echo "    root /var/www/tudestino/apps/web/dist;"
echo "    index index.html;"
echo "    "
echo "    # Security headers"
echo "    add_header X-Frame-Options \"SAMEORIGIN\" always;"
echo "    add_header X-Content-Type-Options \"nosniff\" always;"
echo "    add_header X-XSS-Protection \"1; mode=block\" always;"
echo "    "
echo "    # Handle React Router"
echo "    location / {"
echo "        try_files \$uri \$uri/ /index.html;"
echo "    }"
echo "    "
echo "    # API proxy"
echo "    location /api/ {"
echo "        proxy_pass http://localhost:3000;"
echo "        proxy_http_version 1.1;"
echo "        proxy_set_header Upgrade \$http_upgrade;"
echo "        proxy_set_header Connection 'upgrade';"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
echo "        proxy_cache_bypass \$http_upgrade;"
echo "    }"
echo "    "
echo "    # Socket.IO"
echo "    location /socket.io/ {"
echo "        proxy_pass http://localhost:3000;"
echo "        proxy_http_version 1.1;"
echo "        proxy_set_header Upgrade \$http_upgrade;"
echo "        proxy_set_header Connection \"upgrade\";"
echo "        proxy_set_header Host \$host;"
echo "    }"
echo "    "
echo "    # Uploads"
echo "    location /uploads/ {"
echo "        alias /var/www/tudestino/apps/api/uploads/;"
echo "        expires 30d;"
echo "    }"
echo "}"
echo "EOF"
echo ""

echo "11. Configurar Nginx para la API:"
echo "    cat > /etc/nginx/sites-available/api.tudestino.lat << 'EOF'"
echo "server {"
echo "    listen 80;"
echo "    server_name api.tudestino.lat;"
echo "    return 301 https://\$server_name\$request_uri;"
echo "}"
echo ""
echo "server {"
echo "    listen 443 ssl http2;"
echo "    server_name api.tudestino.lat;"
echo "    "
echo "    location / {"
echo "        proxy_pass http://localhost:3000;"
echo "        proxy_http_version 1.1;"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
echo "    }"
echo "    "
echo "    location /uploads/ {"
echo "        alias /var/www/tudestino/apps/api/uploads/;"
echo "        expires 30d;"
echo "    }"
echo "}"
echo "EOF"
echo ""

echo "12. Habilitar sitios en Nginx:"
echo "    ln -sf /etc/nginx/sites-available/tudestino.lat /etc/nginx/sites-enabled/"
echo "    ln -sf /etc/nginx/sites-available/api.tudestino.lat /etc/nginx/sites-enabled/"
echo "    rm -f /etc/nginx/sites-enabled/default"
echo "    nginx -t"
echo "    systemctl reload nginx"
echo ""

echo "13. Ejecutar migraciones de base de datos:"
echo "    cd /var/www/tudestino/apps/api"
echo "    npm run seed:mysql"
echo ""

echo "14. Iniciar API con PM2:"
echo "    mkdir -p /var/log/pm2"
echo "    cd /var/www/tudestino/apps/api"
echo "    pm2 delete tudestino-api 2>/dev/null || true"
echo "    pm2 start ecosystem.config.cjs"
echo "    pm2 save"
echo "    pm2 startup"
echo ""

echo "15. Configurar variables de entorno para la web:"
echo "    cd /var/www/tudestino/apps/web"
echo "    cat > .env << 'EOF'"
echo "VITE_API_URL=https://tudestino.lat/api"
echo "VITE_SOCKET_URL=https://tudestino.lat"
echo "VITE_APP_NAME=TuDestino"
echo "VITE_APP_URL=https://tudestino.lat"
echo "EOF"
echo ""

echo "16. Rebuilding web con las nuevas variables:"
echo "    cd /var/www/tudestino"
echo "    npm run build:web"
echo ""

echo "17. Configurar firewall:"
echo "    ufw allow ssh"
echo "    ufw allow 'Nginx Full'"
echo "    ufw allow 3000"
echo "    echo 'y' | ufw enable"
echo ""

echo "18. Instalar SSL certificates:"
echo "    apt install -y certbot python3-certbot-nginx"
echo "    certbot --nginx -d tudestino.lat -d www.tudestino.lat -d api.tudestino.lat --non-interactive --agree-tos --email admin@tudestino.lat"
echo ""

echo "19. Verificar que todo esté funcionando:"
echo "    pm2 status"
echo "    systemctl status nginx"
echo "    systemctl status mysql"
echo "    curl -I https://tudestino.lat"
echo "    curl -I https://api.tudestino.lat/health"
echo ""

echo "🎉 DEPLOYMENT COMPLETADO!"
echo ""
echo "URLs de acceso:"
echo "- Web: https://tudestino.lat"
echo "- API: https://api.tudestino.lat"
echo "- Health: https://api.tudestino.lat/health"
echo ""
echo "IMPORTANTE: Configurar DNS del dominio:"
echo "A    tudestino.lat      217.154.179.113"
echo "A    www.tudestino.lat  217.154.179.113"
echo "A    api.tudestino.lat  217.154.179.113"