import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import bcrypt from 'bcryptjs';
import sequelize from './database-mysql.js';
import User from '../modules/users/user.model-mysql.js';
import { Property } from '../modules/properties/property.model.sequelize.js';
import Booking from '../modules/bookings/booking.model.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Cargar variables de entorno desde el archivo .env en producción
dotenv.config({ path: join(__dirname, '../../.env') });

const seedDatabase = async () => {
  try {
    // Conectar a MySQL
    await sequelize.authenticate();
    console.log('✅ Conectado a MySQL');

    // Desactivar verificaciones de claves foráneas temporalmente
    await sequelize.query('SET FOREIGN_KEY_CHECKS = 0');

    // Sincronizar modelos (crear tablas si no existen)
    await sequelize.sync({ force: true }); // force: true borra y recrea tablas
    console.log('✅ Tablas creadas/actualizadas');

    // Reactivar verificaciones de claves foráneas
    await sequelize.query('SET FOREIGN_KEY_CHECKS = 1');

    // Crear usuarios de prueba
    const users = [
      {
        name: 'Admin User',
        email: 'admin@tudestino.com',
        password: await bcrypt.hash('admin123', 12),
        role: 'admin',
        isVerified: true,
        isActive: true,
        emailVerified: true,
      },
      {
        name: 'Host Demo',
        email: 'host@tudestino.com',
        password: await bcrypt.hash('host123', 12),
        role: 'host',
        isVerified: true,
        isActive: true,
        emailVerified: true,
        hostRating: 4.8,
        hostReviewCount: 25,
      },
      {
        name: 'Guest Demo',
        email: 'guest@tudestino.com',
        password: await bcrypt.hash('guest123', 12),
        role: 'guest',
        isVerified: true,
        isActive: true,
        emailVerified: true,
      },
    ];

    const createdUsers = await User.bulkCreate(users);
    console.log('✅ Usuarios de prueba creados:');
    console.log('   - admin@tudestino.com / admin123 (Admin)');
    console.log('   - host@tudestino.com / host123 (Host)');
    console.log('   - guest@tudestino.com / guest123 (Guest)');

    // Crear propiedades de prueba
    const hostUser = createdUsers.find(u => u.role === 'host');

    const properties = [
      // ========== PROPIEDADES EN CAJAMARCA, PERÚ ==========
      {
        hostId: hostUser.id,
        title: 'Moderno Apartamento en el Centro de Cajamarca',
        description: 'Hermoso apartamento completamente equipado en pleno centro histórico de Cajamarca. A pasos de la Plaza de Armas, restaurantes y principales atractivos turísticos. Ideal para conocer la ciudad.',
        type: 'apartment',
        address: 'Jr. Amazonas 234',
        city: 'Cajamarca',
        state: 'Cajamarca',
        country: 'Peru',
        zipCode: '06001',
        latitude: -7.1619,
        longitude: -78.5128,
        basePrice: 45.00,
        currency: 'USD',
        cleaningFee: 10.00,
        serviceFee: 8.00,
        guests: 4,
        bedrooms: 2,
        beds: 2,
        bathrooms: 1,
        amenities: ['wifi', 'kitchen', 'heating', 'tv', 'workspace'],
        checkIn: '14:00',
        checkOut: '11:00',
        minimumStay: 1,
        maximumStay: 30,
        smokingAllowed: false,
        petsAllowed: 'no',
        eventsAllowed: false,
        status: 'published',
        isActive: true,
        averageRating: 4.7,
        ratingCount: 23,
      },
      {
        hostId: hostUser.id,
        title: 'Casa Colonial con Vista a las Montañas',
        description: 'Encantadora casa colonial restaurada con impresionantes vistas a las montañas cajamarquinas. Jardín amplio, chimenea y todas las comodidades modernas. Perfecta para familias.',
        type: 'house',
        address: 'Av. Perú 456',
        city: 'Cajamarca',
        state: 'Cajamarca',
        country: 'Peru',
        zipCode: '06002',
        latitude: -7.1580,
        longitude: -78.5090,
        basePrice: 85.00,
        currency: 'USD',
        cleaningFee: 20.00,
        serviceFee: 15.00,
        guests: 8,
        bedrooms: 4,
        beds: 5,
        bathrooms: 3,
        amenities: ['wifi', 'kitchen', 'heating', 'parking', 'tv', 'workspace', 'balcony'],
        checkIn: '15:00',
        checkOut: '11:00',
        minimumStay: 2,
        maximumStay: 60,
        smokingAllowed: false,
        petsAllowed: 'yes_free',
        eventsAllowed: false,
        status: 'published',
        isActive: true,
        averageRating: 4.9,
        ratingCount: 35,
      },
      {
        hostId: hostUser.id,
        title: 'Habitación Privada cerca de Ventanillas de Otuzco',
        description: 'Acogedora habitación privada en casa familiar, ubicada estratégicamente cerca de las famosas Ventanillas de Otuzco. Desayuno incluido. Los anfitriones te ayudarán con recomendaciones turísticas.',
        type: 'room',
        address: 'Carretera a Otuzco Km 8',
        city: 'Cajamarca',
        state: 'Cajamarca',
        country: 'Peru',
        zipCode: '06003',
        latitude: -7.1450,
        longitude: -78.4850,
        basePrice: 25.00,
        currency: 'USD',
        cleaningFee: 5.00,
        serviceFee: 5.00,
        guests: 2,
        bedrooms: 1,
        beds: 1,
        bathrooms: 1,
        amenities: ['wifi', 'heating', 'parking'],
        checkIn: '13:00',
        checkOut: '11:00',
        minimumStay: 1,
        maximumStay: 14,
        smokingAllowed: false,
        petsAllowed: 'no',
        eventsAllowed: false,
        status: 'published',
        isActive: true,
        averageRating: 4.6,
        ratingCount: 18,
      },
      {
        hostId: hostUser.id,
        title: 'Studio Acogedor cerca de los Baños del Inca',
        description: 'Pequeño pero funcional studio a 5 minutos de los famosos Baños del Inca. Perfecto para viajeros que buscan relajación en las aguas termales. Incluye kitchenette y zona de trabajo.',
        type: 'studio',
        address: 'Av. Manco Cápac 789',
        city: 'Cajamarca',
        state: 'Cajamarca',
        country: 'Peru',
        zipCode: '06004',
        latitude: -7.1630,
        longitude: -78.4650,
        basePrice: 35.00,
        currency: 'USD',
        cleaningFee: 8.00,
        serviceFee: 6.00,
        guests: 2,
        bedrooms: 1,
        beds: 1,
        bathrooms: 1,
        amenities: ['wifi', 'kitchen', 'heating', 'tv', 'workspace'],
        checkIn: '14:00',
        checkOut: '11:00',
        minimumStay: 1,
        maximumStay: 21,
        smokingAllowed: false,
        petsAllowed: 'no',
        eventsAllowed: false,
        status: 'published',
        isActive: true,
        averageRating: 4.5,
        ratingCount: 14,
      },
      {
        hostId: hostUser.id,
        title: 'Villa de Lujo con Piscina y Jardín Privado',
        description: 'Exclusiva villa de lujo en zona residencial premium de Cajamarca. Cuenta con piscina climatizada, jardín amplio, BBQ, sala de juegos y vistas panorámicas. Ideal para grupos grandes o eventos especiales.',
        type: 'villa',
        address: 'Urb. Los Pinos Mz D Lt 15',
        city: 'Cajamarca',
        state: 'Cajamarca',
        country: 'Peru',
        zipCode: '06005',
        latitude: -7.1520,
        longitude: -78.5200,
        basePrice: 180.00,
        currency: 'USD',
        cleaningFee: 40.00,
        serviceFee: 30.00,
        guests: 12,
        bedrooms: 6,
        beds: 8,
        bathrooms: 5,
        amenities: ['wifi', 'kitchen', 'heating', 'pool', 'parking', 'tv', 'workspace', 'gym', 'balcony'],
        checkIn: '16:00',
        checkOut: '12:00',
        minimumStay: 3,
        maximumStay: 90,
        smokingAllowed: false,
        petsAllowed: 'yes_free',
        eventsAllowed: true,
        status: 'published',
        isActive: true,
        averageRating: 5.0,
        ratingCount: 42,
      },
      {
        hostId: hostUser.id,
        title: 'Cabaña Rústica en las Afueras de Cajamarca',
        description: 'Auténtica cabaña de piedra y madera en medio del campo cajamarquino. Perfecta para desconectarse y disfrutar de la naturaleza. Chimenea, fogata exterior y vistas espectaculares al atardecer.',
        type: 'cabin',
        address: 'Camino Rural Los Eucaliptos s/n',
        city: 'Cajamarca',
        state: 'Cajamarca',
        country: 'Peru',
        zipCode: '06006',
        latitude: -7.1800,
        longitude: -78.5350,
        basePrice: 55.00,
        currency: 'USD',
        cleaningFee: 12.00,
        serviceFee: 10.00,
        guests: 6,
        bedrooms: 3,
        beds: 3,
        bathrooms: 2,
        amenities: ['wifi', 'kitchen', 'heating', 'parking', 'workspace'],
        checkIn: '15:00',
        checkOut: '11:00',
        minimumStay: 2,
        maximumStay: 30,
        smokingAllowed: false,
        petsAllowed: 'yes_free',
        eventsAllowed: false,
        status: 'published',
        isActive: true,
        averageRating: 4.8,
        ratingCount: 27,
      },
      {
        hostId: hostUser.id,
        title: 'Apartamento Económico para Mochileros',
        description: 'Apartamento sencillo y económico ideal para viajeros de presupuesto ajustado. Ubicación céntrica, cocina compartida y ambiente amigable. Perfecto para conocer otros viajeros.',
        type: 'apartment',
        address: 'Jr. Dos de Mayo 567',
        city: 'Cajamarca',
        state: 'Cajamarca',
        country: 'Peru',
        zipCode: '06007',
        latitude: -7.1640,
        longitude: -78.5100,
        basePrice: 20.00,
        currency: 'USD',
        cleaningFee: 5.00,
        serviceFee: 3.00,
        guests: 3,
        bedrooms: 1,
        beds: 2,
        bathrooms: 1,
        amenities: ['wifi', 'kitchen', 'heating'],
        checkIn: '12:00',
        checkOut: '10:00',
        minimumStay: 1,
        maximumStay: 15,
        smokingAllowed: false,
        petsAllowed: 'no',
        eventsAllowed: false,
        status: 'published',
        isActive: true,
        averageRating: 4.3,
        ratingCount: 9,
      },
      {
        hostId: hostUser.id,
        title: 'Casa Familiar con Patio y Huerta Orgánica',
        description: 'Linda casa familiar con amplio patio y huerta orgánica. Los huéspedes pueden cosechar verduras frescas para cocinar. Ambiente tranquilo y familiar, ideal para quienes buscan experiencia local auténtica.',
        type: 'house',
        address: 'Psje. Santa Rosa 123',
        city: 'Cajamarca',
        state: 'Cajamarca',
        country: 'Peru',
        zipCode: '06008',
        latitude: -7.1590,
        longitude: -78.5180,
        basePrice: 65.00,
        currency: 'USD',
        cleaningFee: 15.00,
        serviceFee: 12.00,
        guests: 6,
        bedrooms: 3,
        beds: 4,
        bathrooms: 2,
        amenities: ['wifi', 'kitchen', 'heating', 'parking', 'tv', 'workspace'],
        checkIn: '14:00',
        checkOut: '11:00',
        minimumStay: 2,
        maximumStay: 45,
        smokingAllowed: false,
        petsAllowed: 'yes_free',
        eventsAllowed: false,
        status: 'published',
        isActive: true,
        averageRating: 4.7,
        ratingCount: 21,
      },
      {
        hostId: hostUser.id,
        title: 'Loft Moderno con Diseño Contemporáneo',
        description: 'Espectacular loft de diseño minimalista con techos altos, ventanales amplios y decoración contemporánea. Ubicado en el corazón de Cajamarca. Ideal para profesionales y parejas que aprecian el buen diseño.',
        type: 'apartment',
        address: 'Av. San Martín 890',
        city: 'Cajamarca',
        state: 'Cajamarca',
        country: 'Peru',
        zipCode: '06009',
        latitude: -7.1600,
        longitude: -78.5140,
        basePrice: 75.00,
        currency: 'USD',
        cleaningFee: 18.00,
        serviceFee: 14.00,
        guests: 4,
        bedrooms: 2,
        beds: 2,
        bathrooms: 2,
        amenities: ['wifi', 'kitchen', 'heating', 'tv', 'workspace', 'balcony'],
        checkIn: '15:00',
        checkOut: '12:00',
        minimumStay: 2,
        maximumStay: 60,
        smokingAllowed: false,
        petsAllowed: 'no',
        eventsAllowed: false,
        status: 'published',
        isActive: true,
        averageRating: 4.9,
        ratingCount: 31,
      },
      {
        hostId: hostUser.id,
        title: 'Habitación Doble con Baño Privado - Vista al Jardín',
        description: 'Cómoda habitación doble con baño privado en casa de familia. Vista al jardín con flores nativas. Incluye desayuno típico cajamarquino. Los anfitriones organizan tours a Cumbemayo y otros atractivos.',
        type: 'room',
        address: 'Jr. Junín 345',
        city: 'Cajamarca',
        state: 'Cajamarca',
        country: 'Peru',
        zipCode: '06010',
        latitude: -7.1625,
        longitude: -78.5095,
        basePrice: 30.00,
        currency: 'USD',
        cleaningFee: 6.00,
        serviceFee: 5.00,
        guests: 2,
        bedrooms: 1,
        beds: 1,
        bathrooms: 1,
        amenities: ['wifi', 'heating', 'tv'],
        checkIn: '13:00',
        checkOut: '11:00',
        minimumStay: 1,
        maximumStay: 20,
        smokingAllowed: false,
        petsAllowed: 'no',
        eventsAllowed: false,
        status: 'published',
        isActive: true,
        averageRating: 4.8,
        ratingCount: 25,
      },
      {
        hostId: hostUser.id,
        title: 'Villa Campestre con Caballerizas',
        description: 'Magnífica villa campestre en las afueras de Cajamarca con caballerizas y establos. Perfecta para amantes de los caballos. Se ofrecen paseos a caballo por los alrededores. Entorno natural privilegiado.',
        type: 'villa',
        address: 'Fundo Los Alamos Km 12',
        city: 'Cajamarca',
        state: 'Cajamarca',
        country: 'Peru',
        zipCode: '06011',
        latitude: -7.1350,
        longitude: -78.5450,
        basePrice: 150.00,
        currency: 'USD',
        cleaningFee: 35.00,
        serviceFee: 25.00,
        guests: 10,
        bedrooms: 5,
        beds: 6,
        bathrooms: 4,
        amenities: ['wifi', 'kitchen', 'heating', 'parking', 'tv', 'workspace', 'balcony'],
        checkIn: '15:00',
        checkOut: '12:00',
        minimumStay: 3,
        maximumStay: 60,
        smokingAllowed: false,
        petsAllowed: 'yes_free',
        eventsAllowed: true,
        status: 'published',
        isActive: true,
        averageRating: 4.9,
        ratingCount: 38,
      },
      {
        hostId: hostUser.id,
        title: 'Studio Premium con Terraza Panorámica',
        description: 'Exclusivo studio en el último piso con terraza panorámica de 360° con vistas a toda la ciudad de Cajamarca. Mobiliario de alta calidad, cocina gourmet y jacuzzi privado en la terraza.',
        type: 'studio',
        address: 'Jr. Lima 678 - Piso 5',
        city: 'Cajamarca',
        state: 'Cajamarca',
        country: 'Peru',
        zipCode: '06012',
        latitude: -7.1610,
        longitude: -78.5120,
        basePrice: 95.00,
        currency: 'USD',
        cleaningFee: 22.00,
        serviceFee: 18.00,
        guests: 2,
        bedrooms: 1,
        beds: 1,
        bathrooms: 1,
        amenities: ['wifi', 'kitchen', 'heating', 'tv', 'workspace', 'balcony'],
        checkIn: '16:00',
        checkOut: '12:00',
        minimumStay: 2,
        maximumStay: 30,
        smokingAllowed: false,
        petsAllowed: 'no',
        eventsAllowed: false,
        status: 'published',
        isActive: true,
        averageRating: 5.0,
        ratingCount: 19,
      },
      {
        hostId: hostUser.id,
        title: 'Cabaña Ecológica con Paneles Solares',
        description: 'Innovadora cabaña ecológica construida con materiales sostenibles, paneles solares y sistema de recolección de agua de lluvia. Para viajeros conscientes del medio ambiente. Rodeada de naturaleza virgen.',
        type: 'cabin',
        address: 'Sector Las Lomas s/n',
        city: 'Cajamarca',
        state: 'Cajamarca',
        country: 'Peru',
        zipCode: '06013',
        latitude: -7.1750,
        longitude: -78.5300,
        basePrice: 70.00,
        currency: 'USD',
        cleaningFee: 15.00,
        serviceFee: 12.00,
        guests: 4,
        bedrooms: 2,
        beds: 2,
        bathrooms: 1,
        amenities: ['wifi', 'kitchen', 'heating', 'workspace'],
        checkIn: '14:00',
        checkOut: '11:00',
        minimumStay: 2,
        maximumStay: 21,
        smokingAllowed: false,
        petsAllowed: 'yes_free',
        eventsAllowed: false,
        status: 'published',
        isActive: true,
        averageRating: 4.8,
        ratingCount: 16,
      },

      // ========== PROPIEDADES EN MÉXICO (originales) ==========
      {
        hostId: hostUser.id,
        title: 'Hermoso apartamento con vista al mar',
        description: 'Disfruta de impresionantes vistas al océano desde este moderno apartamento. Perfecto para parejas o familias pequeñas.',
        type: 'apartment',
        address: 'Av. Costera 123',
        city: 'Cancún',
        state: 'Quintana Roo',
        country: 'México',
        zipCode: '77500',
        latitude: 21.1619,
        longitude: -86.8515,
        basePrice: 120.00,
        currency: 'USD',
        cleaningFee: 25.00,
        serviceFee: 15.00,
        guests: 4,
        bedrooms: 2,
        beds: 2,
        bathrooms: 2,
        amenities: ['wifi', 'kitchen', 'ac', 'pool', 'parking', 'tv'],
        checkIn: '15:00',
        checkOut: '11:00',
        minimumStay: 2,
        maximumStay: 30,
        smokingAllowed: false,
        petsAllowed: 'no',
        eventsAllowed: false,
        status: 'published',
        isActive: true,
        averageRating: 4.8,
        ratingCount: 15,
      },
      {
        hostId: hostUser.id,
        title: 'Casa de playa con acceso privado',
        description: 'Relájate en esta espaciosa casa de playa con acceso directo a la arena blanca. Ideal para vacaciones familiares.',
        type: 'house',
        address: 'Calle Playa 456',
        city: 'Playa del Carmen',
        state: 'Quintana Roo',
        country: 'México',
        zipCode: '77710',
        latitude: 20.6296,
        longitude: -87.0739,
        basePrice: 250.00,
        currency: 'USD',
        cleaningFee: 50.00,
        serviceFee: 30.00,
        guests: 8,
        bedrooms: 4,
        beds: 5,
        bathrooms: 3,
        amenities: ['wifi', 'kitchen', 'ac', 'pool', 'parking', 'tv', 'washer', 'balcony'],
        checkIn: '16:00',
        checkOut: '10:00',
        minimumStay: 3,
        maximumStay: 60,
        smokingAllowed: false,
        petsAllowed: 'yes_free',
        eventsAllowed: false,
        status: 'published',
        isActive: true,
        averageRating: 4.9,
        ratingCount: 28,
      },
      {
        hostId: hostUser.id,
        title: 'Acogedora cabaña en la montaña',
        description: 'Escapa del ruido de la ciudad en esta encantadora cabaña rodeada de naturaleza.',
        type: 'cabin',
        address: 'Carretera Nacional km 45',
        city: 'Valle de Bravo',
        state: 'Estado de México',
        country: 'México',
        zipCode: '51200',
        latitude: 19.1952,
        longitude: -100.1326,
        basePrice: 90.00,
        currency: 'USD',
        cleaningFee: 20.00,
        serviceFee: 10.00,
        guests: 6,
        bedrooms: 3,
        beds: 3,
        bathrooms: 2,
        amenities: ['wifi', 'kitchen', 'heating', 'parking', 'workspace'],
        checkIn: '14:00',
        checkOut: '12:00',
        minimumStay: 1,
        maximumStay: 14,
        smokingAllowed: false,
        petsAllowed: 'yes_free',
        eventsAllowed: false,
        status: 'published',
        isActive: true,
        averageRating: 4.7,
        ratingCount: 12,
      },
    ];

    const createdProperties = await Property.bulkCreate(properties);
    console.log(`✅ Propiedades de prueba creadas (${properties.length}): ${properties.filter(p => p.city === 'Cajamarca').length} en Cajamarca, Peru + ${properties.filter(p => p.country === 'México').length} en México`);

    // Crear reservas de prueba
    const guestUser = createdUsers.find(u => u.role === 'guest');
    const today = new Date();
    const futureDate = new Date(today);
    futureDate.setDate(today.getDate() + 30);
    const pastDate = new Date(today);
    pastDate.setDate(today.getDate() - 10);

    const bookings = [
      {
        propertyId: createdProperties[0].id,
        guestId: guestUser.id,
        hostId: hostUser.id,
        checkIn: today.toISOString().split('T')[0],
        checkOut: futureDate.toISOString().split('T')[0],
        guests: 2,
        basePrice: 120.00,
        cleaningFee: 25.00,
        serviceFee: 15.00,
        totalPrice: 3900.00,
        currency: 'USD',
        status: 'confirmed',
        paymentStatus: 'paid',
        guestNotes: 'Looking forward to the stay!',
      },
      {
        propertyId: createdProperties[1].id,
        guestId: guestUser.id,
        hostId: hostUser.id,
        checkIn: pastDate.toISOString().split('T')[0],
        checkOut: today.toISOString().split('T')[0],
        guests: 4,
        basePrice: 250.00,
        cleaningFee: 50.00,
        serviceFee: 30.00,
        totalPrice: 2800.00,
        currency: 'USD',
        status: 'completed',
        paymentStatus: 'paid',
      },
      {
        propertyId: createdProperties[2].id,
        guestId: guestUser.id,
        hostId: hostUser.id,
        checkIn: new Date(today.getTime() + 60 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        checkOut: new Date(today.getTime() + 65 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        guests: 3,
        basePrice: 90.00,
        cleaningFee: 20.00,
        serviceFee: 10.00,
        totalPrice: 470.00,
        currency: 'USD',
        status: 'pending',
        paymentStatus: 'pending',
      },
    ];

    await Booking.bulkCreate(bookings);
    console.log('✅ Reservas de prueba creadas (3)');

    await sequelize.close();
    console.log('✅ Seed completado exitosamente');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error en seed:', error);
    process.exit(1);
  }
};

seedDatabase();
